language: python
python:
  - 3.7
git:
  depth: false

# Ubuntu 20.04 (Focal) LTS
os: linux
dist: focal

# Set the cache
cache:
  pip: true
  directories:
    - "$HOME/.cache/pre-commit"

# Environment variables
env:
  global:
    # Set Matplotlib backend to Agg (Non-interactive, only writes to files)
    - MPLBACKEND=Agg

# Installs poetry, pre-commit, coveralls
before_install:
  - curl -sSL https://install.python-poetry.org | python3 -
  - poetry --version
  - pip install pre-commit
  - pip install coveralls

# Installs all packages needed for tmi in a virtual environment.
# Installs the hooks for checking formatting.
install:
  - poetry install
  - pre-commit install-hooks

# Run the linting (before_script) and run the tests
before_script: pre-commit run --all-files
script: poetry run pytest

jobs:
  include:
    # We can change the python build version here to whatever we decide on.
    - stage: build
      python: 3.7
      script: poetry build

after_success:
  - coveralls

notifications:
  email: false
